<?php
if ($class=='home') {
  # code...
  $home='class="active"';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='master') {
  # code...
  $home='';
  $master='class="active"';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='master_prodi') {
  # code...
  $home='';
  $master='class="active open"';
    $master_prodi='class="active"';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';

}elseif ($class=='master_mk') {
  # code...
  $home='';
  $master='class="active open"';
    $master_prodi='';
    $master_mk='class="active"';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='master_dosen') {
  # code...
  $home='';
  $master='class="active open"';
    $master_prodi='';
    $master_mk='';
    $master_dosen='class="active"';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='master_mhs') {
  # code...
  $home='';
  $master='class="active open"';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='class="active"';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='transaksi') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='class="active"';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='tran_jadwal') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='class="active open"';
    $tran_jadwal='class="active"';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='tran_krs') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='class="active open"';
    $tran_jadwal='';
    $tran_krs='class="active"';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='tran_nilai') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='class="active open"';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='class="active"';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='tran_mutasi_mhs') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='class="active open"';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='class="active"';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='tran_wisuda') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='class="active open"';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='class="active"';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='laporan') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active"';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='lap_mhs') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active open"';
    $lap_mhs='class="active"';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='lap_dosen') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active open"';
    $lap_mhs='';
    $lap_dosen='class="active"';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';

}elseif ($class=='lap_mk') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active open"';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='class="active"';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';

}elseif ($class=='lap_krs') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active open"';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='class=active';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='lap_absen') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active open"';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='class="active"';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='lap_nilai') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active open"';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='class="active"';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='lap_mutasi') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active open"';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='class="active"';
    $lap_wisuda='';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='lap_wisuda') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='class="active open"';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='class="active"';
  $grafik='';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='grafik') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='class="active"';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='gra_mhs') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='class="active open"';
    $gra_mhs='class="active"';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='gra_dosen') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='class="active open"';
    $gra_mhs='';
    $gra_dosen='class="active"';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='gra_mhs_aktf'){
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='class="active open"';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='class="active"';
    $gra_krs='';
    $gra_wisuda='';
}elseif ($class=='gra_krs') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='class="active open"';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='class="active"';
    $gra_wisuda='';

}elseif ($class=='gra_wisuda') {
  # code...
  $home='';
  $master='';
    $master_prodi='';
    $master_mk='';
    $master_dosen='';
    $master_mhs='';
  $transaksi='';
    $tran_jadwal='';
    $tran_krs='';
    $tran_nilai='';
    $tran_mutasi_mhs='';
    $tran_wisuda='';
  $laporan='';
    $lap_mhs='';
    $lap_dosen='';
    $lap_mk='';
    $lap_krs='';
    $lap_absen='';
    $lap_nilai='';
    $lap_mutasi='';
    $lap_wisuda='';
  $grafik='class="active open"';
    $gra_mhs='';
    $gra_dosen='';
    $gra_mhs_aktf='';
    $gra_krs='';
    $gra_wisuda='class="active"';
}
 ?>
